# Site settings
name: Less Or More
email: zhyj2266680@163.com
author: Shadas
url: http://shadas.me
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/shadas/
baseurl: 
description: Actually, less is more!
meta_description: 雨天背锅，背锅。
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: shadas
highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
       short_name : Shadas
    # disqus :
    #    short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
theme: jekyll-theme-cayman